### ISSUE TITLE
Priming process looks like it will just flood the engine

### ISSUE THREAD

**Issue by davidmweber** [ppakotze/RV7POH#2]
The priming process calls for 3-5 seconds of full rate fuel flow into the engine which seems very aggressive when compared to the Scottish Bulldog's process (Bulldog POH pg 4-3). If you have a reference for this process or other information, let me know. We may also just need to settle it by  experimentation.

**Comment by ppakotze-sarao** [comment]
Agree.  
Original came from Lycoming manual for the IO-360 page 3-2 and will share with you.  You will also notice that the temperature / pressure limits in the Lycoming manual are more aggressive than the Bulldogs.

**Comment by davidmweber** [comment]
Lycoming states that you start mixture at idle cutoff with fuel pump on and move mixture to FULL RITCH until you see a "slight but steady" fuel flow for 3-5s. Then switch fuel pump off. My interpretation is you add "just enough" fuel well before you are at full rich so flooding unlikely. If it is OK with you, I will amend the POH accordingly
